import type { Dispatch, SetStateAction } from 'react'

import type { IAccount } from '@e-coop-monorepo/modules/account'
import type {
    IGeneralLedger,
    IGeneralLedgerPaginated,
} from '@e-coop-monorepo/modules/general-ledger'
import type { IMemberJointAccount } from '@e-coop-monorepo/modules/member-joint-account'
import type { IMemberProfile } from '@e-coop-monorepo/modules/member-profile'
import type { IQRMemberProfile } from '@e-coop-monorepo/modules/qr-crypto'
import type { TPaymentMode } from '@e-coop-monorepo/modules/quick-transfer'
import type { TEntityId } from '@e-coop-monorepo/shared/types'
import { create } from 'zustand'

export interface TransactionPropsStore {
    openMemberPicker: boolean
    focusTypePayment: TPaymentMode
    selectedMember: IMemberProfile | null
    openPaymentsEntryModal: boolean
    selectedAccountId: TEntityId | undefined
    isAutoGeneratedOR?: boolean
    selectedJointMember?: IMemberJointAccount | null
    openSuccessModal: boolean
    transactionFormSuccess: IGeneralLedger | null
    openPaymentWithTransactionModal: boolean
    focusedLedger:
        | {
              memberProfileId: TEntityId
              accountId: TEntityId
              account?: IAccount
              memberAccountingLedgerId?: TEntityId
          }
        | undefined
    selectedAccount?: IAccount
    currentPayment: IGeneralLedgerPaginated | null
    decodedMemberProfile?: IQRMemberProfile

    setOpenMemberPicker: Dispatch<SetStateAction<boolean>>
    setFocusTypePayment: (payment: TPaymentMode) => void
    setSelectedMember: (member: IMemberProfile | null) => void
    setOpenPaymentsEntryModal: (open: boolean) => void
    setSelectedAccountId: (accountId: TEntityId | undefined) => void
    setIsAutoGeneratedOR: (isAutoGenerated: boolean) => void
    setSelectedJointMember: (jointMember: IMemberJointAccount | null) => void
    setOpenSuccessModal: (open: boolean) => void
    setTransactionFormSuccess: (transaction: IGeneralLedger | null) => void
    setOpenPaymentWithTransactionModal: (open: boolean) => void
    setSelectedAccount: (accountId?: IAccount) => void
    setGetCurrentPayment: (payment?: IGeneralLedgerPaginated | null) => void
    setDecodedMemberProfile: (profile?: IQRMemberProfile) => void
    handleResetAll: () => void
    setFocusedLedger: (
        focused:
            | {
                  memberProfileId: TEntityId
                  accountId: TEntityId
                  account?: IAccount
                  memberAccountingLedgerId: TEntityId
              }
            | undefined
    ) => void
}

export const useTransactionStore = create<TransactionPropsStore>(
    (set, get) => ({
        focusTypePayment: 'payment',
        selectedMember: null,
        openPaymentsEntryModal: false,
        openMemberPicker: false,
        selectedAccountId: undefined,
        isAutoGeneratedOR: false,
        selectedJointMember: null,
        openSuccessModal: false,
        transactionFormSuccess: null,
        openPaymentWithTransactionModal: false,
        focusedLedger: undefined,
        selectedAccount: undefined,
        currentPayment: null,
        decodedMemberProfile: undefined,

        setSelectedAccountId: (accountId) =>
            set({ selectedAccountId: accountId }),
        setSelectedMember: (member) => set({ selectedMember: member }),
        setOpenPaymentsEntryModal: (open) =>
            set({ openPaymentsEntryModal: open }),
        setFocusTypePayment: (payment) =>
            set({
                focusTypePayment: payment,
                openPaymentWithTransactionModal: true,
            }),
        setOpenMemberPicker: (open) =>
            set({
                openMemberPicker:
                    typeof open === 'function'
                        ? open(get().openMemberPicker)
                        : open,
            }),
        setIsAutoGeneratedOR: (isAutoGenerated) =>
            set({ isAutoGeneratedOR: isAutoGenerated }),
        setSelectedJointMember: (jointMember) =>
            set({ selectedJointMember: jointMember }),
        setOpenSuccessModal: (open) => set({ openSuccessModal: open }),
        setTransactionFormSuccess: (transaction) =>
            set({ transactionFormSuccess: transaction }),
        setOpenPaymentWithTransactionModal: (open) =>
            set({ openPaymentWithTransactionModal: open }),
        setGetCurrentPayment: (payment) =>
            set({ currentPayment: payment ?? null }),

        setDecodedMemberProfile: (profile) =>
            set({ decodedMemberProfile: profile }),

        handleResetAll: () =>
            set(() => ({
                focusTypePayment: 'payment',
                // selectedMember: null,
                openPaymentsEntryModal: false,
                openMemberPicker: false,
                selectedAccountId: undefined,
                isAutoGeneratedOR: false,
                selectedJointMember: null,
                openSuccessModal: false,
                transactionFormSuccess: null,
                openPaymentWithTransactionModal: false,
                currentPayment: null,
                decodedMemberProfile: undefined,
            })),
        setFocusedLedger: (focused) => set({ focusedLedger: focused }),
        setSelectedAccount: (account) =>
            set({
                selectedAccount: account,
            }),
    })
)
