import type { ICONS } from '@/constants'
import {
    AiOutlineDownload as DownloadIcon,
    AiOutlineFullscreenExit as FullscreenExitIcon,
    AiOutlineFullscreen as FullscreenIcon,
    AiFillHome as HomeFillIcon,
    AiOutlineKey as KeyIcon,
    AiOutlineLoading as LoadingCircleIcon,
    AiOutlineLoading3Quarters as LoadingSpinnerIcon,
    AiOutlineMessage as MessageOutlineIcon,
    AiOutlineRotateLeft as RotateBoxLeftIcon,
    AiOutlineRotateRight as RotateBoxRightIcon,
    AiFillShop as ShopIcon,
    AiOutlineClear as SmallBrushIcon,
} from 'react-icons/ai'
import {
    BiErrorCircle as WarningIcon,
    BiSolidZap as ZapIcon,
} from 'react-icons/bi'
import {
    BsRocketTakeoff as BsRocketTakeoffIcon,
    BsBuildingGear as BuildingCogIcon,
    BsRocketTakeoffFill as RocketIcon,
    BsLayoutSidebarInset as SidebarIcon,
    BsLayoutSidebarInsetReverse as SidebarRightIcon,
} from 'react-icons/bs'
import {
    BsFillPatchCheckFill as BadgeCheckFillIcon,
    BsPatchCheck as BadgeCheckIcon,
    BsPatchExclamationFill as BadgeExclamationFillIcon,
    BsPatchExclamation as BadgeExclamationIcon,
    BsFillPatchMinusFill as BadgeMinusFillIcon,
    BsPatchMinusFill as BadgeMinusIcon,
    BsPatchQuestionFill as BadgeQuestionFillIcon,
    BsPatchQuestion as BadgeQuestionIcon,
    BsBuildingGear as BuildingGearIcon,
    BsCameraFill as CameraFillIcon,
    BsUiChecksGrid as ChecksGridIcon,
    BsFileEarmarkCodeFill as CodeFileFillIcon,
    BsCompassFill as CompassIcon,
    BsFileEarmarkZipFill as CompressedFileFillIcon,
    BsCursorFill as CursorFillIcon,
    BsDashSquareDotted as DashSquareDottedIcon,
    BsDatabaseFillLock as DatabaseLockIcon,
    BsFileEarmarkWordFill as DocumentFileFillIcon,
    BsFileEarmarkExcelFill as ExcelFileFillIcon,
    BsFillFastForwardFill as FastForwardIcon,
    BsFileEarmarkFill as FileFillIcon,
    BsFileEarmarkFontFill as FontFileFillIcon,
    BsFillGridFill as GridFillIcon,
    BsGrid1X2Fill as GridIcon,
    BsImage as Image2Icon,
    BsFileEarmarkImageFill as ImageFileFillIcon,
    BsFillInfoCircleFill as InfoFillCircleIcon,
    BsInfo as InfoIcon,
    BsInstagram as InstagramIcon,
    BsFileEarmarkMusicFill as MusicFileFillIcon,
    BsFileEarmarkPdfFill as PDFFileFillIcon,
    BsFileEarmarkPptFill as PresentationFileFillIcon,
    BsFillPrinterFill as PrinterFillIcon,
    BsFillQuestionCircleFill as QuestionCircleFillIcon,
    BsShieldFillCheck as ShieldCheckIcon,
    BsShieldLockFill as ShieldLockIcon,
    BsLayoutSidebar as SidebarLeftIcon,
    BsLayoutSidebarInset as SidebarLeftOpenIcon,
    BsSignpost2Fill as SignPostIcon,
    BsFileEarmarkSpreadsheetFill as SpreadSheetFileIcon,
    BsFileEarmarkTextFill as TextFileFillIcon,
    BsUmbrellaFill as UmbrellaIcon,
    BsPatchCheck as VerifiedPatchIcon,
    BsFileEarmarkPlayFill as VideoFileFillIcon,
    BsZoomIn as ZoomInIcon,
    BsZoomOut as ZoomOutIcon,
} from 'react-icons/bs'
import {
    CgDetailsLess as DetailsIcon,
    CgFacebook as FacebookIcon,
    CgInternal as InternalIcon,
    CgRedo as RedoCircleIcon,
    CgSmartphone as SmartphoneIcon,
    CgUnavailable as UnavailableIcon,
} from 'react-icons/cg'
import {
    CiBarcode as BarcodeScanIcon,
    CiExport as ExportIcon,
    CiFilter as FunnelOutlineIcon,
    CiGlobe as GlobeIcon,
} from 'react-icons/ci'
import {
    FaLocationArrow as ArrowIcon,
    FaMoneyBill as BillIcon,
    FaBookOpen as BookOpenIcon,
    FaBook as BookThickIcon,
    FaBriefcaseMedical as BriefcaseMedicalIcon,
    FaBug as BugIcon,
    FaRegCircle as CircleIcon,
    FaCloud as CloudIcon,
    FaCode as CodeIcon,
    FaCreditCard as CreditCardIcon,
    FaFileCsv as CsvIcon,
    FaBold as FaBoldIcon,
    FaCalendarCheck as FaCalendarCheckIcon,
    FaTimesCircle as FaTimesIcon,
    FaFingerprint as FingerPrintIcon,
    FaGlobeAsia as GlobeAsiaIcon,
    FaGripHorizontal as GripHorizontalIcon,
    FaGripVertical as GripVerticalIcon,
    FaHandsHelping as HandsHelpingIcon,
    FaListUl as ListUIIcon,
    FaRegMap as MapIcon,
    FaMoneyCheckAlt as MoneyCheck2Icon,
    FaPaintBrush as PaintBrushIcon,
    FaPhoneAlt as PhoneIcon,
    FaRunning as RunningIcon,
    FaSort as SortIcon,
    FaStar as StarIcon,
    FaTabletAlt as TabletIcon,
    FaTwitter as TwitterIcon,
    FaUserClock as UserClockFillIcon,
    FaWifi as WifiIcon,
    FaYoutube as YoutubeIcon,
} from 'react-icons/fa'
import {
    FaAddressCard as AddressCardIcon,
    FaFaceAngry as AngryIcon,
    FaArrowTrendUp as ArrowTrendUpIcon,
    FaArrowUpLong as ArrowUpLong,
    // FaShield as ShieldFillIcon
    FaBell as BellIcon,
    FaBoxesStacked as BoxesStackedIcon,
    FaBusinessTime as BriefCaseClockIcon,
    FaChartBar as ChartBarIcon,
    FaCheck as CheckFillIcon,
    FaCookieBite as CookieBiteIcon,
    FaDatabase as DatabaseIcon,
    FaDivide as DivideIcon,
    FaDocker as DockerIcon,
    FaFirstdraft as DraftIcon,
    FaCircleCheck as FaCheckIcon,
    FaGears as GearsIcon,
    FaVenusMars as GendersIcon,
    FaGithub as GithubIcon,
    FaGolang as GolangIcon,
    FaHandHoldingHeart as HandHeartIcon,
    FaHeadset as HeadsetIcon,
    FaHouseChimneyWindow as HouseIcon,
    FaHouseLock as HouseLockIcon,
    FaIdCard as IdCardIcon,
    FaLandmarkFlag as LandmarkIcon,
    FaMoneyCheck as MoneyCheckIcon,
    FaMoneyBillTrendUp as MoneyTrendIcon,
    FaPeopleGroup as PeopleGroupIcon,
    FaPercent as PercentIcon,
    FaPesoSign as PesoIcon,
    FaChartPie as PieChartIcon,
    FaQuestion as QuestionIcon,
    FaReact as ReactIcon,
    FaSchool as SchoolIcon,
    FaShapes as ShapesIcon,
    FaStop as StopIcon,
    FaThumbsDown as ThumbsDownIcon,
    FaThumbsUp as ThumbsUpIcon,
    FaTrash as TrashFillIcon,
    FaTreeCity as TreeCityIcon,
    FaUser as UserFillIcon,
    FaUserLock as UserLockIcon,
    FaUserPlus as UserPlusIcon,
    FaUserShield as UserShieldIcon,
    FaUsersLine as Users3LineIcon,
    FaWandMagicSparkles as WandSparkleIcon,
    FaXTwitter as XTwitterIcon,
} from 'react-icons/fa6'
import {
    FiCamera as CameraIcon,
    FiCodesandbox as CodeSandBox,
    FiEye as EyeIcon,
    FiEyeOff as EyeOffIcon,
    FiHardDrive as HardDriveIcon,
    FiHash as HashIcon,
    FiNavigation as NavigationIcon,
    FiUpload as UploadIcon,
} from 'react-icons/fi'
import {
    GiBorderedShield as BorderedShieldIcon,
    GiBrain as BrainIcon,
    GiTreeBranch as BranchIcon,
    GiDiamondRing as DiamondRingIcon,
    GiFiles as FilesIcon,
    GiGasMask as GasMaskIcon,
    GiClockwork as GiClockIcon,
    GiMoneyStack as GiMoneyStackIcon,
    GiPayMoney as HandDropCoinsIcon,
    GiTakeMyMoney as MoneyIcon,
    GiMoneyStack as MoneyStackIcon,
    GiReceiveMoney as ReceiveMoneyIcon,
    GiVillage as VillageIcon,
    GiVote as VoteIcon,
    GiWallet as WalletIcon,
    GiWoodenSign as WoodSignsIcon,
} from 'react-icons/gi'
import {
    GoArrowLeft as ArrowLeftIcon,
    GoArrowRight as ArrowRightIcon,
    GoDotFill as DotBigIcon,
    GoKebabHorizontal as DotsHorizontalIcon,
    GoHorizontalRule as HorizontalRuleIcon,
    GoSearch as MagnifyingGlassIcon,
    GoOrganization as OrganizationIcon,
} from 'react-icons/go'
import {
    GrMoney as CoinsStackIcon,
    GrView as EyeViewIcon,
    GrVmMaintenance as MaintenanceIcon,
    GrFormNextLink as NextIcon,
    GrPaint as PaintIcon,
    GrPowerReset as PowerResetIcon,
} from 'react-icons/gr'
import {
    HiAdjustmentsHorizontal as AdjustIcon,
    HiChevronDown as ArrowChevronDown,
    HiChevronRight as ArrowChevronRight,
    HiChevronUp as ArrowChevronUpIcon,
    HiOutlineArrowDown as ArrowDownIcon,
    HiArrowDownLeft as ArrowDownLeftIcon,
    HiOutlineArrowsUpDown as ArrowUpDownIcon,
    HiOutlineArrowUp as ArrowUpIcon,
    HiArrowUpRight as ArrowUpRightIcon,
    HiOutlineBriefcase as BriefCaseIcon,
    HiOutlineChevronDown as ChevronDownIcon,
    HiOutlineChevronLeft as ChevronLeftIcon,
    HiOutlineChevronRight as ChevronRightIcon,
    HiOutlineChevronDoubleLeft as ChevronsLeftIcon,
    HiOutlineChevronDoubleRight as ChevronsRightIcon,
    HiViewColumns as ColumnIcon,
    HiOutlineViewColumns as ColumnOutlineIcon,
    HiOutlineSquaresPlus as DashboardIcon,
    HiOutlineCodeBracket as DevIcon,
    HiOutlineChatBubbleBottomCenterText as FeedbackIcon,
    HiFolder as FolderFillIcon,
    HiOutlineArrowRightEndOnRectangle as LogoutIcon,
    HiOutlineChatBubbleOvalLeft as MessagesIcon,
    HiOutlineMoon as MoonIcon,
    HiOutlineNoSymbol as NotAllowedIcon,
    HiOutlineBell as NotificationIcon,
    HiPencil as PencilFillIcon,
    HiOutlinePencil as PencilOutlineIcon,
    HiOutlineQuestionMarkCircle as QuestionCircleIcon,
    HiOutlineCog as SettingsIcon,
    HiShieldExclamation as ShieldExclamationIcon,
    HiSparkles as SparkleIcon,
    HiOutlineSun as SunIcon,
    HiTag as TagIcon,
    HiMiniWrenchScrewdriver as WrenchIcon,
} from 'react-icons/hi2'
import { ImHammer2 as JudgeHammerIcon } from 'react-icons/im'
import {
    IoMdClock as ClockFillIcon,
    IoIosFunnel as FunnelFilledIcon,
    IoIosCog as GearIcon,
    IoIosCode as IoIosCodeIcon,
    IoIosPulse as PulseIcon,
    IoIosClose as XIcon,
} from 'react-icons/io'
import {
    IoReturnDownBackOutline as BackIcon,
    IoCalculator as CalculatorIcon,
    IoCalendar as CalendarDotsIcon,
    IoCalendarNumber as CalendarNumberIcon,
    IoChatbubblesSharp as ChatBubbleIcon,
    IoCheckmarkOutline as CheckIcon,
    IoCloseOutline as CloseIcon,
    IoDiamond as DiamondIcon,
    IoDocumentTextOutline as DocumentOutlineIcon,
    IoLogOut as DoorExitFillIcon,
    IoLogOutOutline as DoorExitIcon,
    IoPencilOutline as EditPencilIcon,
    IoFootstepsOutline as FootstepsIcon,
    IoFunnelOutline as FunnelIcon,
    IoKeySharp as KeySharpIcon,
    IoLanguage as LanguageIcon,
    IoLayers as LayersIcon,
    IoLink as LinkIcon,
    IoLogoLinkedin as LinkedInIcon,
    IoLocationSharp as LocationPinIcon,
    IoLocation as PinLocationIcon,
    IoPricetag as PriceTagIcon,
    IoPrintOutline as PrinterIcon,
    IoReceiptOutline as ReceiptIcon,
    IoReload as ReloadIcon,
    IoShield as ShieldFillIcon,
    IoStorefront as StoreIcon,
    IoSwapHorizontal as SwapArrowIcon,
    IoCallOutline as TelephoneIcon,
    IoTicket as TicketIcon,
    IoTrendingDown as TrendingDownIcon,
    IoTrendingUp as TrendingUpIcon,
} from 'react-icons/io5'
import {
    LiaMapMarkedAltSolid as MapMarkedIcon,
    LiaShieldAltSolid as ShieldIcon,
    LiaUserClockSolid as UserClockIcon,
    LiaUserCogSolid as UserCogIcon,
    LiaUser as UserIcon,
    LiaUserTagSolid as UserTagIcon,
} from 'react-icons/lia'
import type { IconBaseProps } from 'react-icons/lib'
import {
    LuCalendarCheck as CalendarCheckIcon,
    LuCalendar as CalendarIcon,
    LuCameraOff as CameraOffIcon,
    LuChevronsUpDown as ChevronsUpDownIcon,
    LuClock8 as ClockIcon,
    LuCopy as CopyIcon,
    LuCrown as CrownIcon,
    LuFileX as FileXIcon,
    LuHardDriveUpload as HardDriveUploadIcon,
    LuHeading as HeadingIcon,
    LuHistory as HistoryIcon,
    LuImage as ImageIcon,
    LuListOrdered as ListOrderedIcon,
    LuMonitorCog as MonitorCogIcon,
    LuExternalLink as OpenExternalLinkIcon,
    LuSend as PaperPlaneIcon,
    LuQrCode as QrCodeIcon,
    LuRedo2 as RedoIcon,
    LuReplace as ReplaceIcon,
    LuScanLine as ScanLineIcon,
    LuScanQrCode as ScanQrIcon,
    LuTrash as TrashIcon,
    LuUndo2 as UndoIcon,
    LuView as ViewIcon,
    LuScale as WeightScaleIcon,
} from 'react-icons/lu'
import {
    MdManageAccounts as AccountSettingIcon,
    MdOutlineManageAccounts as AccountSetupIcon,
    MdAccountBalance as AccountsIcon,
    MdOutlineKeyboardArrowUp as ArrowUpLongIcon,
    MdAutoAwesome as AutoAwesomeIcon,
    MdOutlineAccountBalance as BankIcon,
    MdFlipCameraAndroid as CameraFlipIcon,
    MdCameraEnhance as CameraSelectIcon,
    MdOutlineDraw as DrawIcon,
    MdMarkEmailRead as EmailCheckIcon,
    MdOutlineEmail as EmailIcon,
    MdError as ErrorExclamationIcon,
    MdOutlineExpandLess as ExpandLessIcon,
    MdExpandMore as ExpandMoreIcon,
    MdFamilyRestroom as FamilyIcon,
    MdOutlineFilterVintage as FilterVintageIcon,
    MdOutlineQueryStats as FinanceReportsIcon,
    MdOutlineCenterFocusWeak as FocusIcon,
    MdOutlineScreenshotMonitor as MonitorIcon,
    MdOutlinePayments as OutlinePaymentIcon,
    MdOutlinePayments as PaymentsIcon,
    MdOutlineLocalPhone as PhoneOutlineIcon,
    MdLocalPolice as PoliceBadgeIcon,
    MdRestore as RestoreIcon,
    MdOutlineRotate90DegreesCcw as Rotate90DegreeLeftIcon,
    MdOutlineRotate90DegreesCw as Rotate90DegreeRightIcon,
    MdRotateLeft as RotateLeftIcon,
    MdRotateRight as RotateRightIcon,
    MdOutlineSavings as SavingsIcon,
    MdShoppingCart as ShoppingCartIcon,
    MdGroups as UserGroupIcon,
    MdOutlineGroupAdd as UsersAddIcon,
} from 'react-icons/md'
import {
    PiBankDuotone as BankDuoToneIcon,
    PiBuildingOffice as BuildingBranchIcon,
    PiBuilding as BuildingIcon,
    PiCakeFill as CakeIcon,
    PiCodeBlock as CodeBlockIcon,
    PiBracketsCurly as CurlyBracketIcon,
    PiDesktopTowerFill as DesktopTowerIcon,
    PiDevices as DevicesIcon,
    PiWarningDiamondFill as DiamondWarningIcon,
    PiEmpty as EmptyIcon,
    PiMicrosoftExcelLogoFill as ExcelIcon,
    PiGraduationCapFill as GraduationCapIcon,
    PiHandCoinsDuotone as HandCoinsIcon,
    PiHandDepositDuotone as HandDepositIcon,
    PiHandWithdrawDuotone as HandWithdrawIcon,
    PiHeartBreakFill as HeartBreakFillIcon,
    PiListBulletsBold as ListBulletsBoldIcon,
    PiNotepadDuotone as NoteIcon,
    PiContactlessPaymentDuotone as OnlinePaymentIcon,
    PiParkDuotone as ParkIcon,
    PiHandDeposit as PiHandDepositIcon,
    PiHandWithdraw as PiHandWithdrawIcon,
    PiPiggyBankFill as PiggyBankIcon,
    PiPlayLight as PlayIcon,
    PiPlugsConnectedFill as PlugConnectFillIcon,
    PiPlus as PlusIcon,
    PiPushPin as PushPinIcon,
    PiPushPinSlash as PushPinSlashIcon,
    PiNewspaper as ReportsIcon,
    PiSignatureLight as SignatureLightIcon,
    PiTextStrikethroughLight as TextStrikethroughLightIcon,
    PiUserList as UserListIcon,
    PiUsersThreeFill as Users3FillIcon,
    PiUsersThree as Users3Icon,
    PiWarningCircleFill as WarningCircleIcon,
    PiWarningFill as WarningFillIcon,
} from 'react-icons/pi'
import {
    RiCommandLine as CommandIcon,
    RiVipDiamondFill as DiamondFillIcon,
    RiFlipHorizontalFill as FlipHorizontalIcon,
    RiFlipHorizontalLine as FlipHorizontalLineIcon,
    RiFlipVerticalFill as FlipVerticalIcon,
    RiFlipVerticalLine as FlipVerticalLineIcon,
    RiCommunityFill as RiCommunityFillIcon,
    RiRobot2Line as RobotIcon,
    RiListCheck3 as TransactionListIcon,
} from 'react-icons/ri'
import {
    RxDotFilled as DotMediumIcon,
    RxDotsVertical as DotsVerticalIcon,
    RxDragHandleDots2 as DragHandleIcon,
    RxEyeNone as EyeNoneIcon,
    RxMixerHorizontal as MixerHorizontalIcon,
    RxReload as RefreshIcon,
    RxReset as ResetIcon,
    RxRowSpacing as RowSpacingIcon,
    RxFontItalic as ToolbarItalicIcon,
} from 'react-icons/rx'
import {
    SiBookstack as BookStackIcon,
    SiGitbook as SigiBookIcon,
} from 'react-icons/si'
import { SlOptions as OptionsIcon } from 'react-icons/sl'
import {
    TbBlockquote as BlockQuoteIcon,
    TbClockDollar as CashClockIcon,
    TbClockCancel as ClockCancelIcon,
    TbCreditCard as CreditCardIcon2,
    TbCurrencyDollar as DollarIcon,
    TbSquareF1 as F1Icon,
    TbSquareF2 as F2Icon,
    TbSquareF3 as F3Icon,
    TbFingerprintOff as FingerprintOffIcon,
    TbFingerprintScan as FingerprintScanIcon,
    TbGhost2Filled as GhostIcon,
    TbHeartHandshake as HandShakeHeartIcon,
    TbMinus as MinusIcon,
    TbMoneybag as MoneyBagIcon,
    TbGrowth as PlantGrowthIcon,
    TbRecycle as RecycleIcon,
    TbReportSearch as ReportsSearchIcon,
    TbSunMoon as SunMoonIcon,
    TbTargetArrow as TargetArrowIcon,
    TbTransactionDollar as TransactionDollarIcon,
    TbUnlink as UnlinkIcon,
} from 'react-icons/tb'
import { TfiFaceSad as SadFaceIcon } from 'react-icons/tfi'
import {
    TiBook as BookIcon,
    TiPipette as PipetteIcon,
    // TiArrowUp as ArrowUpIcon,
} from 'react-icons/ti'
import {
    VscBracketError as BracketErrorIcon,
    VscCollapseAll as CollapseIcon,
    VscCommentDraft as CommentDashedIcon,
    VscError as ErrorIcon,
    VscExclude as ExcludeIcon,
    VscLayersDot as LayersSharpDotIcon,
    VscLocation as LocationPinOutlineIcon,
    VscReferences as ReferencesIcon,
} from 'react-icons/vsc'

export {
    PesoIcon,
    VoteIcon,
    WifiIcon,
    DiamondFillIcon,
    DiamondIcon,
    BrainIcon,
    FingerprintOffIcon,
    FingerprintScanIcon,
    FingerPrintIcon,
    ArrowUpLongIcon,
    GolangIcon,
    ReactIcon,
    GithubIcon,
    DockerIcon,
    DatabaseIcon,
    CloudIcon,
    RobotIcon,
    RocketIcon,
    PulseIcon,
    SidebarLeftIcon,
    SidebarLeftOpenIcon,
    ArrowChevronUpIcon,
    CircleIcon,
    ChartBarIcon,
    PipetteIcon,
    HeadsetIcon,
    CodeIcon,
    XIcon,
    F1Icon,
    F2Icon,
    F3Icon,
    MapIcon,
    CsvIcon,
    BellIcon,
    SunIcon,
    KeyIcon,
    DevIcon,
    BugIcon,
    EyeIcon,
    TagIcon,
    BookIcon,
    ViewIcon,
    StopIcon,
    PlayIcon,
    CakeIcon,
    NoteIcon,
    CopyIcon,
    BankIcon,
    PlusIcon,
    BillIcon,
    UndoIcon,
    RedoIcon,
    UserIcon,
    MoonIcon,
    DrawIcon,
    StarIcon,
    ParkIcon,
    LinkIcon,
    GearIcon,
    HashIcon,
    BackIcon,
    NextIcon,
    InfoIcon,
    ShopIcon,
    DraftIcon,
    GlobeIcon,
    GhostIcon,
    AngryIcon,
    MoneyIcon,
    EmptyIcon,
    MinusIcon,
    ErrorIcon,
    FileXIcon,
    TrashIcon,
    ClockIcon,
    CloseIcon,
    EmailIcon,
    ImageIcon,
    CheckIcon,
    PhoneIcon,
    CrownIcon,
    ExcelIcon,
    StoreIcon,
    ResetIcon,
    HouseIcon,
    ArrowIcon,
    FocusIcon,
    FunnelIcon,
    ColumnIcon,
    TicketIcon,
    TabletIcon,
    UnlinkIcon,
    FamilyIcon,
    ReloadIcon,
    QrCodeIcon,
    DotBigIcon,
    CameraIcon,
    LayersIcon,
    FaBoldIcon,
    ShieldIcon,
    Users3Icon,
    BranchIcon,
    LogoutIcon,
    ScanQrIcon,
    ExportIcon,
    ZoomInIcon,
    ShapesIcon,
    FilesIcon,
    AdjustIcon,
    UploadIcon,
    WalletIcon,
    DivideIcon,
    UserFillIcon,
    HandHeartIcon,
    ClockFillIcon,
    GridFillIcon,
    FastForwardIcon,
    SchoolIcon,
    Image2Icon,
    IdCardIcon,
    HardDriveIcon,
    EyeOffIcon,
    WrenchIcon,
    GasMaskIcon,
    CommandIcon,
    SadFaceIcon,
    TwitterIcon,
    CashClockIcon,
    EyeViewIcon,
    CodeSandBox,
    ExcludeIcon,
    ReceiptIcon,
    PrinterIcon,
    SavingsIcon,
    HeadingIcon,
    DetailsIcon,
    ReplaceIcon,
    WarningIcon,
    MonitorIcon,
    OptionsIcon,
    ZapIcon,
    UserCogIcon,
    GendersIcon,
    RefreshIcon,
    RunningIcon,
    ArrowUpIcon,
    SidebarIcon,
    SunMoonIcon,
    ZoomOutIcon,
    TrashFillIcon,
    VillageIcon,
    DevicesIcon,
    ReportsIcon,
    PushPinIcon,
    EyeNoneIcon,
    UserTagIcon,
    PercentIcon,
    FaCheckIcon,
    SparkleIcon,
    FaTimesIcon,
    ArrowUpLong,
    DiamondWarningIcon,
    YoutubeIcon,
    GiClockIcon,
    HistoryIcon,
    ScanLineIcon,
    UserPlusIcon,
    GearsIcon,
    MonitorCogIcon,
    CollapseIcon,
    LandmarkIcon,
    SignPostIcon,
    InternalIcon,
    UserLockIcon,
    XTwitterIcon,
    LanguageIcon,
    BookOpenIcon,
    PriceTagIcon,
    UmbrellaIcon,
    QuestionIcon,
    PieChartIcon,
    AccountsIcon,
    PaymentsIcon,
    CompassIcon,
    HomeFillIcon,
    FacebookIcon,
    SettingsIcon,
    LinkedInIcon,
    UserListIcon,
    ThumbsUpIcon,
    MessagesIcon,
    FeedbackIcon,
    BuildingIcon,
    DownloadIcon,
    CalendarIcon,
    FileFillIcon,
    UsersAddIcon,
    TreeCityIcon,
    KeySharpIcon,
    MoneyBagIcon,
    SigiBookIcon,
    DoorExitIcon,
    CursorFillIcon,
    PiggyBankIcon,
    CheckFillIcon,
    HandCoinsIcon,
    MapMarkedIcon,
    BookStackIcon,
    CodeBlockIcon,
    ArrowLeftIcon,
    BriefCaseIcon,
    ArrowDownIcon,
    CameraOffIcon,
    InstagramIcon,
    DotMediumIcon,
    FootstepsIcon,
    UserClockIcon,
    DashboardIcon,
    BookThickIcon,
    IoIosCodeIcon,
    HouseLockIcon,
    WoodSignsIcon,
    TelephoneIcon,
    UserGroupIcon,
    SwapArrowIcon,
    RestoreIcon,
    GlobeAsiaIcon,
    ThumbsDownIcon,
    CookieBiteIcon,
    Users3LineIcon,
    ReferencesIcon,
    ChecksGridIcon,
    NavigationIcon,
    ShieldLockIcon,
    MoneyStackIcon,
    MoneyCheckIcon,
    FolderFillIcon,
    ArrowRightIcon,
    CoinsStackIcon,
    SmartphoneIcon,
    NotAllowedIcon,
    PencilFillIcon,
    SmallBrushIcon,
    PaperPlaneIcon,
    FullscreenIcon,
    RotateLeftIcon,
    CalculatorIcon,
    DatabaseLockIcon,
    RowSpacingIcon,
    PowerResetIcon,
    BlockQuoteIcon,
    InfoFillCircleIcon,
    DragHandleIcon,
    CameraFillIcon,
    EditPencilIcon,
    BadgeMinusIcon,
    BadgeCheckIcon,
    EmailCheckIcon,
    ShieldFillIcon,
    MoneyTrendIcon,
    CameraFlipIcon,
    ExpandLessIcon,
    ExpandMoreIcon,
    CreditCardIcon,
    ChatBubbleIcon,
    UserShieldIcon,
    ListUIIcon,
    Users3FillIcon,
    DollarIcon,
    PaintBrushIcon,
    RedoCircleIcon,
    TrendingUpIcon,
    WeightScaleIcon,
    PeopleGroupIcon,
    TargetArrowIcon,
    PlantGrowthIcon,
    MoneyCheck2Icon,
    CreditCardIcon2,
    PinLocationIcon,
    UnavailableIcon,
    MaintenanceIcon,
    WarningFillIcon,
    ShieldCheckIcon,
    AddressCardIcon,
    ArrowUpDownIcon,
    ChevronLeftIcon,
    BuildingCogIcon,
    ListOrderedIcon,
    RotateRightIcon,
    LocationPinIcon,
    PrinterFillIcon,
    HandDepositIcon,
    ChevronDownIcon,
    PDFFileFillIcon,
    WandSparkleIcon,
    BankDuoToneIcon,
    BarcodeScanIcon,
    AutoAwesomeIcon,
    JudgeHammerIcon,
    PoliceBadgeIcon,
    ClockCancelIcon,
    ReceiveMoneyIcon,
    TrendingDownIcon,
    HandsHelpingIcon,
    DoorExitFillIcon,
    ArrowUpRightIcon,
    OrganizationIcon,
    CalendarDotsIcon,
    BracketErrorIcon,
    ArrowTrendUpIcon,
    BoxesStackedIcon,
    NotificationIcon,
    ChevronsLeftIcon,
    TextFileFillIcon,
    CurlyBracketIcon,
    PhoneOutlineIcon,
    DesktopTowerIcon,
    FlipVerticalIcon,
    FunnelFilledIcon,
    PushPinSlashIcon,
    DotsVerticalIcon,
    ChevronRightIcon,
    CameraSelectIcon,
    SidebarRightIcon,
    HandWithdrawIcon,
    BuildingGearIcon,
    ArrowChevronDown,
    GiMoneyStackIcon,
    AccountSetupIcon,
    BadgeQuestionIcon,
    DiamondRingIcon,
    ShoppingCartIcon,
    RecycleIcon,
    VideoFileFillIcon,
    MusicFileFillIcon,
    ImageFileFillIcon,
    CompressedFileFillIcon,
    CodeFileFillIcon,
    FontFileFillIcon,
    PresentationFileFillIcon,
    ArrowDownLeftIcon,
    ExcelFileFillIcon,
    GraduationCapIcon,
    RotateBoxLeftIcon,
    ToolbarItalicIcon,
    ChevronsRightIcon,
    FunnelOutlineIcon,
    CalendarCheckIcon,
    WarningCircleIcon,
    VerifiedPatchIcon,
    OnlinePaymentIcon,
    LoadingCircleIcon,
    PencilOutlineIcon,
    UserClockFillIcon,
    CommentDashedIcon,
    ArrowChevronRight,
    HandDropCoinsIcon,
    ColumnOutlineIcon,
    PiHandDepositIcon,
    ReportsSearchIcon,
    OutlinePaymentIcon,
    DotsHorizontalIcon,
    FinanceReportsIcon,
    LayersSharpDotIcon,
    SignatureLightIcon,
    HandShakeHeartIcon,
    FlipHorizontalIcon,
    QuestionCircleIcon,
    RotateBoxRightIcon,
    BadgeCheckFillIcon,
    BadgeMinusFillIcon,
    BuildingBranchIcon,
    LoadingSpinnerIcon,
    ChevronsUpDownIcon,
    AccountSettingIcon,
    FullscreenExitIcon,
    MessageOutlineIcon,
    HeartBreakFillIcon,
    BriefCaseClockIcon,
    BorderedShieldIcon,
    CalendarNumberIcon,
    HorizontalRuleIcon,
    PiHandWithdrawIcon,
    DocumentOutlineIcon,
    BsRocketTakeoffIcon,
    PlugConnectFillIcon,
    FaCalendarCheckIcon,
    MagnifyingGlassIcon,
    SpreadSheetFileIcon,
    BriefcaseMedicalIcon,
    HardDriveUploadIcon,
    ListBulletsBoldIcon,
    MixerHorizontalIcon,
    TransactionListIcon,
    RiCommunityFillIcon,
    ErrorExclamationIcon,
    DashSquareDottedIcon,
    OpenExternalLinkIcon,
    FlipVerticalLineIcon,
    BadgeExclamationIcon,
    DocumentFileFillIcon,
    ShieldExclamationIcon,
    BadgeQuestionFillIcon,
    TransactionDollarIcon,
    LocationPinOutlineIcon,
    QuestionCircleFillIcon,
    FlipHorizontalLineIcon,
    Rotate90DegreeLeftIcon,
    Rotate90DegreeRightIcon,
    BadgeExclamationFillIcon,
    TextStrikethroughLightIcon,
    PaintIcon,
    GripHorizontalIcon,
    GripVerticalIcon,
    GridIcon,
    FilterVintageIcon,
    SortIcon,
}

export const IconMap = {
    Brain: BrainIcon,
    FilterVintage: FilterVintageIcon,
    DiamondWarning: DiamondWarningIcon,
    HandDropCoins: HandDropCoinsIcon,
    MoneyStack: MoneyStackIcon,
    HandDepositCoins: HandDepositIcon,
    Vote: VoteIcon,
    'Fingerprint Off': FingerprintOffIcon,
    'Fingerprint Scan': FingerprintScanIcon,
    Fingerprint: FingerPrintIcon,
    'Transaction Dollar': TransactionDollarIcon,
    Golang: GolangIcon,
    React: ReactIcon,
    Github: GithubIcon,
    Docker: DockerIcon,
    Robot: RobotIcon,
    Rocket: RocketIcon,
    Pulse: PulseIcon,
    SidebarLeft: SidebarLeftIcon,
    ArrowChevronUp: ArrowChevronUpIcon,
    GripHorizontal: GripHorizontalIcon,
    GripVertical: GripVerticalIcon,
    Circle: CircleIcon,
    Pipette: PipetteIcon,
    Headset: HeadsetIcon,
    X: XIcon,
    F1: F1Icon,
    F2: F2Icon,
    F3: F3Icon,
    Tag: TagIcon,
    Map: MapIcon,
    CSV: CsvIcon,
    Sun: SunIcon,
    Key: KeyIcon,
    Dev: DevIcon,
    Eye: EyeIcon,
    Book: BookIcon,
    View: ViewIcon,
    Stop: StopIcon,
    Peso: PesoIcon,
    Play: PlayIcon,
    Note: NoteIcon,
    Copy: CopyIcon,
    Bank: BankIcon,
    Plus: PlusIcon,
    Bill: BillIcon,
    Undo: UndoIcon,
    Redo: RedoIcon,
    User: UserIcon,
    Moon: MoonIcon,
    Info: InfoIcon,
    Draw: DrawIcon,
    Park: ParkIcon,
    Link: LinkIcon,
    Gear: GearIcon,
    Hash: HashIcon,
    Back: BackIcon,
    Next: NextIcon,
    Globe: GlobeIcon,
    Ghost: GhostIcon,
    Money: MoneyIcon,
    Empty: EmptyIcon,
    Minus: MinusIcon,
    Error: ErrorIcon,
    Trash: TrashIcon,
    Clock: ClockIcon,
    Close: CloseIcon,
    Email: EmailIcon,
    Zap: ZapIcon,
    Image: ImageIcon,
    Check: CheckIcon,
    Phone: PhoneIcon,
    Excel: ExcelIcon,
    Store: StoreIcon,
    Reset: ResetIcon,
    House: HouseIcon,
    Crown: CrownIcon,
    Column: ColumnIcon,
    Camera: CameraIcon,
    Layers: LayersIcon,
    Shield: ShieldIcon,
    Branch: BranchIcon,
    Logout: LogoutIcon,
    Export: ExportIcon,
    Adjust: AdjustIcon,
    Wallet: WalletIcon,
    School: SchoolIcon,
    'Shopping Cart': ShoppingCartIcon,
    Tablet: TabletIcon,
    Unlink: UnlinkIcon,
    Family: FamilyIcon,
    'List UI': ListUIIcon,
    Reload: ReloadIcon,
    Shapes: ShapesIcon,
    'File X': FileXIcon,
    Ticket: TicketIcon,
    Twitter: TwitterIcon,
    Exclude: ExcludeIcon,
    Receipt: ReceiptIcon,
    'User Fill': UserFillIcon,
    Recycle: RecycleIcon,
    'Fast Forward': FastForwardIcon,
    Printer: PrinterIcon,
    Savings: SavingsIcon,
    Details: DetailsIcon,
    'Diamond Ring': DiamondRingIcon,
    Replace: ReplaceIcon,
    Warning: WarningIcon,
    Monitor: MonitorIcon,
    Options: OptionsIcon,
    Genders: GendersIcon,
    Refresh: RefreshIcon,
    Sidebar: SidebarIcon,
    Village: VillageIcon,
    Reports: ReportsIcon,
    Percent: PercentIcon,
    'Hard Drive': HardDriveIcon,
    Youtube: YoutubeIcon,
    'Scan QR': ScanQrIcon,
    'Image 2': Image2Icon,
    'ID Card': IdCardIcon,
    'Zoom In': ZoomInIcon,
    'Users 3': Users3Icon,
    'FA Bold': FaBoldIcon,
    'QR Code': QrCodeIcon,
    Files: FilesIcon,
    'Dot Big': DotBigIcon,
    Angry: AngryIcon,
    Compass: CompassIcon,
    Landmark: LandmarkIcon,
    Language: LanguageIcon,
    Accounts: AccountsIcon,
    Payments: PaymentsIcon,
    Linkedin: LinkedInIcon,
    Divide: DivideIcon,
    Internal: InternalIcon,
    Facebook: FacebookIcon,
    Settings: SettingsIcon,
    Messages: MessagesIcon,
    Feedback: FeedbackIcon,
    Building: BuildingIcon,
    Download: DownloadIcon,
    'Diamond fill': DiamondFillIcon,
    Calendar: CalendarIcon,
    Heading: HeadingIcon,
    Running: RunningIcon,
    'Arrow Up': ArrowUpIcon,
    'User Cog': UserCogIcon,
    Grid: GridFillIcon,
    'Restore Icon': RestoreIcon,
    'Cash Clock': CashClockIcon,
    'Eye View': EyeViewIcon,
    'Push Pin': PushPinIcon,
    'Sun Moon': SunMoonIcon,
    'Zoom Out': ZoomOutIcon,
    'Clock Fill': ClockFillIcon,
    XTwitter: XTwitterIcon,
    'Printer Fill': PrinterFillIcon,
    'Swap Arrow': SwapArrowIcon,
    'Eye None': EyeNoneIcon,
    'Trend Up': TrendingUpIcon,
    Dollar: DollarIcon,
    'Trash Fill': TrashFillIcon,
    'Cookie Bite': CookieBiteIcon,
    'Trend Down': TrendingDownIcon,
    Calculator: CalculatorIcon,
    'Eye Off': EyeOffIcon,
    'User Tag': UserTagIcon,
    'FA Check': FaCheckIcon,
    'FA Times': FaTimesIcon,
    Gears: GearsIcon,
    'Sad Face': SadFaceIcon,
    Devices: DevicesIcon,
    Footsteps: FootstepsIcon,
    Dashboard: DashboardIcon,
    IoIosCode: IoIosCodeIcon,
    Telephone: TelephoneIcon,
    'File Fill': FileFillIcon,
    'Database Lock': DatabaseLockIcon,
    'Exit Door Fill': DoorExitFillIcon,
    'Exit Door': DoorExitIcon,
    'Upload Icon': UploadIcon,
    'User List': UserListIcon,
    Bug: BugIcon,
    'Hand Heart': HandHeartIcon,
    Diamond: DiamondIcon,
    'Plant Growth': PlantGrowthIcon,
    'Users Add': UsersAddIcon,
    'Tree City': TreeCityIcon,
    'Key Sharp': KeySharpIcon,
    'Money Bag': MoneyBagIcon,
    'Gas Mask': GasMaskIcon,
    Sparkle: SparkleIcon,
    PiggyBank: PiggyBankIcon,
    Star: StarIcon,
    Umbrella: UmbrellaIcon,
    'Judge Hammer': JudgeHammerIcon,
    Cursor: CursorFillIcon,
    'Money Trend': MoneyTrendIcon,
    'Book Open': BookOpenIcon,
    'Price Tag': PriceTagIcon,
    'Pie Chart': PieChartIcon,
    'Thumbs Up': ThumbsUpIcon,
    'Thumbs Down': ThumbsDownIcon,
    Cake: CakeIcon,
    'User Lock': UserLockIcon,
    'Sign Post': SignPostIcon,
    'User Plus': UserPlusIcon,
    QUestion: QuestionIcon,
    'Home Fill': HomeFillIcon,
    Smartphone: SmartphoneIcon,
    'Scan Line': ScanLineIcon,
    References: ReferencesIcon,
    Navigation: NavigationIcon,
    Fullscreen: FullscreenIcon,
    Instagram: InstagramIcon,
    'Book Stack': BookStackIcon,
    Wifi: WifiIcon,
    'Code SandBox': CodeSandBox,
    'House Lock': HouseLockIcon,
    'Check Fill': CheckFillIcon,
    'Hand Coins': HandCoinsIcon,
    'Map Marked': MapMarkedIcon,
    'Code Block': CodeBlockIcon,
    'Arrow Left': ArrowLeftIcon,
    'Brief Case': BriefCaseIcon,
    'Monitor Cog': MonitorCogIcon,
    'Arrow Down': ArrowDownIcon,
    'Camera Off': CameraOffIcon,
    'Dot Medium': DotMediumIcon,
    'User Clock': UserClockIcon,
    'Wood Signs': WoodSignsIcon,
    'User Group': UserGroupIcon,
    'Book Thick': BookThickIcon,
    'Warning Diamond': DiamondWarningIcon,
    'Arrow Up Long': ArrowUpLongIcon,
    Unavailable: UnavailableIcon,
    Maintenance: MaintenanceIcon,
    'Collapse All': CollapseIcon,
    'Gi Clock Icon': GiClockIcon,
    'Checks Grid': ChecksGridIcon,
    'Shield Lock': ShieldLockIcon,
    'Money Stack': MoneyStackIcon,
    'Money Check': MoneyCheckIcon,
    'Paper Plane': PaperPlaneIcon,
    'Folder Fill': FolderFillIcon,
    'Arrow Right': ArrowRightIcon,
    'Coins Stack': CoinsStackIcon,
    'Pencil Fill': PencilFillIcon,
    'Small Brush': SmallBrushIcon,
    'Rotate Left': RotateLeftIcon,
    'Power Reset': PowerResetIcon,
    'Paint Brush': PaintBrushIcon,
    'Block Quote': BlockQuoteIcon,
    'Drag Handle': DragHandleIcon,
    'Camera Fill': CameraFillIcon,
    'Edit Pencil': EditPencilIcon,
    'Badge Minus': BadgeMinusIcon,
    'Badge Check': BadgeCheckIcon,
    'Email Check': EmailCheckIcon,
    'Camera Flip': CameraFlipIcon,
    'Credit Card': CreditCardIcon,
    'User Shield': UserShieldIcon,
    'Shield Fill': ShieldFillIcon,
    'Not Allowed': NotAllowedIcon,
    'Row Spacing': RowSpacingIcon,
    'Expand Less': ExpandLessIcon,
    'Expand More': ExpandMoreIcon,
    'Police Badge': PoliceBadgeIcon,
    'Chat Bubbles': ChatBubbleIcon,
    Organization: OrganizationIcon,
    'Users 3 Fill': Users3FillIcon,
    Notification: NotificationIcon,
    'Users 3 Line': Users3LineIcon,
    'Target Arrow': TargetArrowIcon,
    'Weight Scale': WeightScaleIcon,
    'Pin Location': PinLocationIcon,
    'Warning Fill': WarningFillIcon,
    'Shield Check': ShieldCheckIcon,
    'Address Card': AddressCardIcon,
    'Chevron Left': ChevronLeftIcon,
    Bell: BellIcon,
    'Sidebar Left': SidebarLeftIcon,
    'Building Cog': BuildingCogIcon,
    'List Ordered': ListOrderedIcon,
    'Rotate Right': RotateRightIcon,
    'Location Pin': LocationPinIcon,
    'Hand Deposit': HandDepositIcon,
    'Chevron Down': ChevronDownIcon,
    'Bank DuoTone': BankDuoToneIcon,
    'Barcode Scan': BarcodeScanIcon,
    'People Group': PeopleGroupIcon,
    'Wand Sparkle': WandSparkleIcon,
    'Arrow Up Down': ArrowUpDownIcon,
    'PDF File Fill': PDFFileFillIcon,
    'Money Check 2': MoneyCheck2Icon,
    'Credit Card 2': CreditCardIcon2,
    'Curly Bracket': CurlyBracketIcon,
    'Desktop Tower': DesktopTowerIcon,
    'Bracket Error': BracketErrorIcon,
    'Calendar Dots': CalendarDotsIcon,
    'Boxes Stacked': BoxesStackedIcon,
    'Chevrons Left': ChevronsLeftIcon,
    'Phone Outline': PhoneOutlineIcon,
    'Flip Vertical': FlipVerticalIcon,
    'Funnel Filled': FunnelFilledIcon,
    'Dots Vertical': DotsVerticalIcon,
    'Chevron Right': ChevronRightIcon,
    'Camera Select': CameraSelectIcon,
    'Sidebar Right': SidebarRightIcon,
    'Hand Withdraw': HandWithdrawIcon,
    'GiMoney Stack': GiMoneyStackIcon,
    'Account Setup': AccountSetupIcon,
    'Hands Helping': HandsHelpingIcon,
    'Building Gear': BuildingGearIcon,
    'Push Pin Slash': PushPinSlashIcon,
    'Arrow Trend Up': ArrowTrendUpIcon,
    'Text File Fill': TextFileFillIcon,
    'Badge Question': BadgeQuestionIcon,
    'Graduation Cap': GraduationCapIcon,
    'Toolbar Italic': ToolbarItalicIcon,
    'Chevrons Right': ChevronsRightIcon,
    'Funnel Outline': FunnelOutlineIcon,
    'Calendar Check': CalendarCheckIcon,
    'Warning Circle': WarningCircleIcon,
    'Verified Patch': VerifiedPatchIcon,
    'Online Payment': OnlinePaymentIcon,
    'Loading Circle': LoadingCircleIcon,
    'Pencil Outline': PencilOutlineIcon,
    'Comment Dashed': CommentDashedIcon,
    'Column Outline': ColumnOutlineIcon,
    'User Clock Fill': UserClockFillIcon,
    'Video File Fill': VideoFileFillIcon,
    'Hand Drop Coins': HandDropCoinsIcon,
    'Music File Fill': MusicFileFillIcon,
    'Image File Fill': ImageFileFillIcon,
    'Excel File Fill': ExcelFileFillIcon,
    'Rotate Box Left': RotateBoxLeftIcon,
    'Finance Reports': FinanceReportsIcon,
    'Signature Light': SignatureLightIcon,
    'Flip Horizontal': FlipHorizontalIcon,
    'Question Circle': QuestionCircleIcon,
    'Building Branch': BuildingBranchIcon,
    'Loading Spinner': LoadingSpinnerIcon,
    'Account Setting': AccountSettingIcon,
    'Fullscreen Exit': FullscreenExitIcon,
    'Message Outline': MessageOutlineIcon,
    'Calendar Number': CalendarNumberIcon,
    'Arrow Chevron Down': ArrowChevronDown,
    'Chevrons Up Down': ChevronsUpDownIcon,
    'Heart Break Fill': HeartBreakFillIcon,
    'Layers Sharp Dot': LayersSharpDotIcon,
    'Hand Shake Heart': HandShakeHeartIcon,
    'Rotate Box Right': RotateBoxRightIcon,
    'Badge Check Fill': BadgeCheckFillIcon,
    'Badge Minus Fill': BadgeMinusFillIcon,
    'Brief Case Clock': BriefCaseClockIcon,
    'Magnifying Glass': MagnifyingGlassIcon,
    'Mixer Horizontal': MixerHorizontalIcon,
    'Transaction List': TransactionListIcon,
    'Spread Sheet File': SpreadSheetFileIcon,
    'Arrow Chevron Right': ArrowChevronRight,
    'Plug Connect Fill': PlugConnectFillIcon,
    'FA Calendar Check': FaCalendarCheckIcon,
    'Hard Drive Upload': HardDriveUploadIcon,
    'List Bullets Bold': ListBulletsBoldIcon,
    'Error Exclamation': ErrorExclamationIcon,
    'Badge Exclamation': BadgeExclamationIcon,
    'Medkit Briefcase': BriefcaseMedicalIcon,
    'Document File Fill': DocumentFileFillIcon,
    'Dash Square Dotted': DashSquareDottedIcon,
    'Open External Link': OpenExternalLinkIcon,
    'Flip Vertical Line': FlipVerticalLineIcon,
    'Bordered Shield Icon': BorderedShieldIcon,
    'Horizontal Rule Icon': HorizontalRuleIcon,
    'Shield Exclamation': ShieldExclamationIcon,
    'Badge Question Fill': BadgeQuestionFillIcon,
    'Ri Community Fill Icon': RiCommunityFillIcon,
    'Location Pin Outline': LocationPinOutlineIcon,
    'Question Circle Fill': QuestionCircleFillIcon,
    'Flip Horizontal Line': FlipHorizontalLineIcon,
    'Rotate 90 Degree Left': Rotate90DegreeLeftIcon,
    'Rotate 90 Degree Right': Rotate90DegreeRightIcon,
    'Badge Exclamation Fill': BadgeExclamationFillIcon,
    'Text Strikethrough Light': TextStrikethroughLightIcon,
    'Lu History Icon': HistoryIcon,
    'Outline Payment': OutlinePaymentIcon,
    'Pi Hand Deposit': PiHandDepositIcon,
    'Pi Hand Withdraw': PiHandWithdrawIcon,
    'Auto Awesome': AutoAwesomeIcon,
    'Arrow Icon': ArrowIcon,
    'Redo Circle Icon': RedoCircleIcon,
    'Focus Icon': FocusIcon,
    'Command Icon': CommandIcon,
    'Code Icon': CodeIcon,
    'Clock Cancel': ClockCancelIcon,
    'Wrench Icon': WrenchIcon,
    'Draft Icon': DraftIcon,
    'Chart Bar': ChartBarIcon,
    Cloud: CloudIcon,
    Database: DatabaseIcon,
    'Globe Asia': GlobeAsiaIcon,
    'Shop Icon': ShopIcon,
    'Grid Icon': GridIcon,
    'Receive Money': ReceiveMoneyIcon,
    'Report Search Icon': ReportsSearchIcon,
    'Sort Icon': SortIcon,
}

export type TIcon = (typeof ICONS)[number]

export const RenderIcon = ({
    icon,
    ...props
}: { icon: TIcon } & IconBaseProps) => {
    const FoundIcon = IconMap[icon]

    if (FoundIcon === undefined) return

    return <FoundIcon {...props} />
}
