import { useCallback } from 'react'

import { useNavigate } from '@tanstack/react-router'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'

import { standardSchemaResolver } from '@hookform/resolvers/standard-schema'

import { useAuthUserWithOrgBranch } from '@/modules/authentication/authgentication.store'
import { IGeneralLedger } from '@/modules/general-ledger'
import {
    TTransactionFormSchema,
    TransactionFromSchema,
    useGetTransactionById,
} from '@/modules/transaction'
import { useTransactionBatchStore } from '@/modules/transaction-batch/store/transaction-batch-store'
import { useTransactionReverseSecurityStore } from '@/store/transaction-reverse-security-store'
import { useHotkeys } from 'react-hotkeys-hook'

import { useModalState } from '@/hooks/use-modal-state'
import { useSubscribe } from '@/hooks/use-pubsub'
import { useQeueryHookCallback } from '@/hooks/use-query-hook-cb'

import { TEntityId } from '@/types'

import { paymentORResolver } from '../transaction.utils'

// Navigation helper
const useTransactionNavigation = (fullPath: string) => {
    const navigate = useNavigate()
    return {
        open: (id: TEntityId) =>
            navigate({ to: fullPath, search: { transactionId: id } }),
        clear: () => navigate({ to: fullPath, search: {} }),
    }
}

export type UseTransactionControllerProps = {
    fullPath: string
    transactionId?: TEntityId
    newOR: string
    isAutoGenerated: boolean
}

export const useTransactionController = ({
    transactionId,
    fullPath,
    newOR,
    isAutoGenerated,
}: UseTransactionControllerProps) => {
    const navigate = useTransactionNavigation(fullPath)

    const {
        currentAuth: { user_organization },
    } = useAuthUserWithOrgBranch()

    const {
        settings_accounting_payment_default_value,
        settings_accounting_payment_default_value_id,
        settings_payment_type_default_value_id,
        allow_withdraw_negative_balance,
    } = user_organization

    const transactionReverse = useTransactionReverseSecurityStore()
    const modalTransactionReverseState = useTransactionReverseSecurityStore()

    const { hasNoTransactionBatch, data: currentTransactionBatch } =
        useTransactionBatchStore()

    // Form
    const finalPaymentOR = paymentORResolver(user_organization)

    const form = useForm<TTransactionFormSchema>({
        resolver: standardSchemaResolver(TransactionFromSchema),
        defaultValues: {
            reference_number: newOR,
            or_auto_generated: isAutoGenerated,
        },
    })

    const selectedMember = form.getValues('member_profile')
    const selectedMemberId = form.getValues('member_profile_id')

    const resetTransaction = useCallback(() => {
        navigate.clear()
        form.reset({
            reference_number: finalPaymentOR,
            or_auto_generated: isAutoGenerated,
            member_profile: undefined,
            member_profile_id: undefined,
            general_ledger_id: undefined,
        })
    }, [navigate, form, finalPaymentOR, isAutoGenerated])

    //Fetch transaction
    const {
        data: transaction,
        isError,
        isSuccess,
        refetch: refetchTransaction,
        isLoading: isLoadingTransaction,
    } = useGetTransactionById({
        id: transactionId ?? '',
        options: { enabled: !!transactionId },
    })

    const handleError = useCallback((error: Error) => {
        toast.error(error?.message || 'Something went wrong')
    }, [])

    useQeueryHookCallback({
        data: transaction,
        error: handleError,
        isError,
        isSuccess,
        onSuccess: (tx) => {
            if (!tx.member_profile) return

            form.setValue('member_profile', tx.member_profile)
            form.setValue('member_profile_id', tx.member_profile_id)
        },
    })

    //    Subscriptions (safe)
    useSubscribe(
        `member_occupation_history.create.member_profile.${selectedMemberId}`
    )
    useSubscribe(
        `member_occupation_history.update.member_profile.${selectedMemberId}`
    )
    useSubscribe(
        `member_occupation_history.delete.member_profile.${selectedMemberId}`
    )

    useSubscribe(`transaction.create.${transactionId}`)
    useSubscribe(`transaction.update.${transactionId}`)

    //    Hotkeys
    useHotkeys(
        'Escape',
        (e) => {
            e.preventDefault()
            resetTransaction()
        },
        { enableOnFormTags: true },
        [resetTransaction]
    )

    //    Modals (grouped)
    const modals = {
        paymentSuccess: useModalState(),
        accountPicker: useModalState(),
        memberScanner: useModalState(),
        ledger: useModalState(),
        accountPayment: useModalState(),
        loanPayment: useModalState(),
        othersCollapsible: useModalState(),
        history: useModalState(),
    }

    //      2Return API
    return {
        ...modals,
        ...transactionReverse,

        transactionId,
        fullPath,
        navigate,

        transaction,
        refetchTransaction,
        isLoadingTransaction,

        form,
        generalLedger: form.getValues('general_ledger') as IGeneralLedger,

        selectedMember,
        selectedMemberId,
        hasSelectedMember: !!selectedMember,

        hasNoTransactionBatch,
        currentTransactionBatch,

        modalTransactionReverseState,

        settings_accounting_payment_default_value,
        settings_accounting_payment_default_value_id,
        settings_payment_type_default_value_id,
        allow_withdraw_negative_balance,

        finalPaymentOR,
        isAutoGeneratedForm: !form.getValues('or_auto_generated'),
        user_organization,

        handlers: {
            removeMember: () => {
                form.setValue('member_profile', undefined)
                form.setValue('member_profile_id', undefined)
            },
            resetTransaction,
        },
    }
}

export type TTransactionControllerReturn = ReturnType<
    typeof useTransactionController
>
