import React, { createContext, useContext } from 'react'

import { FormProvider } from 'react-hook-form'

import { useGetUserSettings } from '@/modules/user-profile'

import { TEntityId } from '@/types'

import {
    TTransactionControllerReturn,
    useTransactionController,
} from '../hooks/use-transaction-controller'
import { paymentORResolver } from '../transaction.utils'

export interface ITransactionFeatureContext extends TTransactionControllerReturn {}

type TTransactipnProviderProps = {
    children: React.ReactNode
    transactionId?: TEntityId
    fullPath: string
}

export const TransactionProvider = ({
    children,
    transactionId,
    fullPath,
}: TTransactipnProviderProps) => {
    const { payment_or_allow_user_input, userOrganization, ORWithPadding } =
        useGetUserSettings()
    const isAutoGenerated = !payment_or_allow_user_input

    const newOR = isAutoGenerated
        ? paymentORResolver(userOrganization)
        : ORWithPadding

    const controller = useTransactionController({
        transactionId,
        fullPath,
        newOR,
        isAutoGenerated,
    })

    return (
        <TransactionFeatureContext.Provider value={controller}>
            <FormProvider {...controller.form}>{children}</FormProvider>
        </TransactionFeatureContext.Provider>
    )
}

const TransactionFeatureContext =
    createContext<ITransactionFeatureContext | null>(null)

export const useTransactionContext = () => {
    const context = useContext(TransactionFeatureContext)
    if (!context)
        throw new Error(
            'useTransactionFeature must be used within TransactionProvider'
        )
    return context
}
