export const FAMILY_RELATIONSHIP = [
    'Father',
    'Mother',
    'Son',
    'Daughter',
    'Brother',
    'Sister',
    'Husband',
    'Wife',
    'Partner',
    'Grandfather',
    'Grandmother',
    'Grandson',
    'Granddaughter',
    'Stepfather',
    'Stepmother',
    'Stepson',
    'Stepdaughter',
    'Half-Brother',
    'Half-Sister',
    'Foster Father',
    'Foster Mother',
    'Foster Son',
    'Foster Daughter',
    'Guardian',
    'Uncle',
    'Aunt',
    'Nephew',
    'Niece',
    'Cousin',
    'Father-in-Law',
    'Mother-in-Law',
    'Son-in-Law',
    'Daughter-in-Law',
    'Brother-in-Law',
    'Sister-in-Law',
    'Godfather',
    'Godmother',
    'Godson',
    'Goddaughter',
    'Adopted Son',
    'Adopted Daughter',
    'Ward',
    'Other',
] as const
