import { useCallback, useEffect } from 'react'

import { useNavigate } from '@tanstack/react-router'
import { useForm, useWatch } from 'react-hook-form'
import { toast } from 'sonner'

import { standardSchemaResolver } from '@hookform/resolvers/standard-schema'

import { useAuthUserWithOrgBranch } from '@/modules/authentication/authgentication.store'
import {
    TTransactionFormSchema,
    TransactionFromSchema,
    useGetTransactionById,
} from '@/modules/transaction'
import { useTransactionBatchStore } from '@/modules/transaction-batch/store/transaction-batch-store'
import { useTransactionReverseSecurityStore } from '@/store/transaction-reverse-security-store'
import { useHotkeys } from 'react-hotkeys-hook'

import { useModalState } from '@/hooks/use-modal-state'
import { useQeueryHookCallback } from '@/hooks/use-query-hook-cb'

import { TEntityId } from '@/types'

import { paymentORResolver } from '../transaction.utils'

// Navigation helper
const useTransactionNavigation = (fullPath: string) => {
    const navigate = useNavigate()
    return {
        open: (id: TEntityId) =>
            navigate({ to: fullPath, search: { transactionId: id } }),
        clear: () => navigate({ to: fullPath, search: {} }),
    }
}

export type UseTransactionControllerProps = {
    fullPath: string
    transactionId?: TEntityId
    // newOR: string
    // isAutoGenerated: boolean
}

export const useTransactionController = ({
    transactionId,
    fullPath,
}: UseTransactionControllerProps) => {
    const navigate = useTransactionNavigation(fullPath)

    const {
        currentAuth: { user_organization },
    } = useAuthUserWithOrgBranch()

    const {
        settings_accounting_payment_default_value,
        settings_accounting_payment_default_value_id,
        settings_payment_type_default_value_id,
        allow_withdraw_negative_balance,
    } = user_organization

    const transactionReverse = useTransactionReverseSecurityStore()
    const modalTransactionReverseState = useTransactionReverseSecurityStore()

    const { hasNoTransactionBatch, data: currentTransactionBatch } =
        useTransactionBatchStore()

    // Form
    const finalPaymentOR = paymentORResolver(user_organization)

    const form = useForm<TTransactionFormSchema>({
        resolver: standardSchemaResolver(TransactionFromSchema),
        defaultValues: {
            reference_number: finalPaymentOR,
        },
    })

    const handleAutoGenerateOR = useCallback(
        (isAuto?: boolean) => {
            form.setValue('or_auto_generated', isAuto)
            if (!user_organization)
                return toast.warning(
                    'Failed to generate Payment OR, could not retrieve settings'
                )

            if (isAuto) {
                form.setValue('reference_number', finalPaymentOR)
            }
        },
        [user_organization, form, finalPaymentOR]
    )

    const selectedMember = useWatch({
        control: form.control,
        name: 'member_profile',
    })
    const selectedMemberId = useWatch({
        control: form.control,
        name: 'member_profile_id',
    })
    const generalLedger = useWatch({
        control: form.control,
        name: 'general_ledger',
    })
    const resetTransaction = useCallback(() => {
        navigate.clear()
        form.reset({
            reference_number: finalPaymentOR,
            or_auto_generated:
                !user_organization?.payment_or_allow_user_input ||
                user_organization?.payment_auto_increment,
            member_profile: undefined,
            member_profile_id: undefined,
            general_ledger_id: undefined,
        })
    }, [navigate, form, finalPaymentOR, user_organization])

    //Fetch transaction
    const {
        data: transaction,
        isError,
        isSuccess,
        refetch: refetchTransaction,
        isLoading: isLoadingTransaction,
    } = useGetTransactionById({
        id: transactionId ?? '',
        options: { enabled: !!transactionId },
    })

    const handleError = useCallback((error: Error) => {
        toast.error(error?.message || 'Something went wrong')
    }, [])

    useQeueryHookCallback({
        data: transaction,
        error: handleError,
        isError,
        isSuccess,
    })

    useEffect(() => {
        const shouldGenerate =
            !form.getValues('reference_number') &&
            (!user_organization?.payment_or_allow_user_input ||
                user_organization?.payment_auto_increment)

        if (!shouldGenerate) return

        handleAutoGenerateOR(true)
    }, [user_organization, form, handleAutoGenerateOR])

    useEffect(() => {
        if (!transaction) return

        form.reset({
            ...form.getValues(),
            reference_number: transaction.reference_number,
            member_profile: transaction.member_profile,
            member_profile_id: transaction.member_profile_id,
        })
    }, [transaction, form])

    //    Hotkeys
    useHotkeys(
        'Escape',
        (e) => {
            e.preventDefault()
            resetTransaction()
        },
        { enableOnFormTags: true },
        [resetTransaction]
    )

    //    Modals (grouped)
    const modals = {
        paymentSuccess: useModalState(),
        accountPicker: useModalState(),
        memberScanner: useModalState(),
        ledger: useModalState(),
        accountPayment: useModalState(),
        loanPayment: useModalState(),
        othersCollapsible: useModalState(),
        history: useModalState(),
    }

    //      2Return API
    return {
        ...modals,
        ...transactionReverse,

        transactionId,
        fullPath,
        navigate,

        transaction,
        refetchTransaction,
        isLoadingTransaction,

        form,
        generalLedger,

        selectedMember,
        selectedMemberId,
        hasSelectedMember: !!selectedMember,

        hasNoTransactionBatch,
        currentTransactionBatch,

        modalTransactionReverseState,

        settings_accounting_payment_default_value,
        settings_accounting_payment_default_value_id,
        settings_payment_type_default_value_id,
        allow_withdraw_negative_balance,

        finalPaymentOR,
        isAutoGeneratedForm: !form.getValues('or_auto_generated'),
        user_organization,

        handlers: {
            removeMember: () => {
                form.setValue('member_profile', undefined)
                form.setValue('member_profile_id', undefined)
            },
            resetTransaction,
        },
    }
}

export type TTransactionControllerReturn = ReturnType<
    typeof useTransactionController
>
