/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as dashboardProfileRouteImport } from './routes/(dashboard)/profile'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as landingAboutRouteImport } from './routes/(landing)/about'
import { Route as landingCalculatorRouteImport } from './routes/(landing)/calculator'
import { Route as landingContactUsRouteImport } from './routes/(landing)/contact-us'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as landingRouteRouteImport } from './routes/(landing)/route'
import { Route as landingTermsRouteImport } from './routes/(landing)/terms'
import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthJoinRouteImport } from './routes/auth/join'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as PlaygroundRouteImport } from './routes/playground'

const PlaygroundRoute = PlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => rootRouteImport,
} as any)
const landingRouteRoute = landingRouteRouteImport.update({
    id: '/(landing)',
    getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
    id: '/(dashboard)',
    getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => landingRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => AuthRouteRoute,
} as any)
const AuthJoinRoute = AuthJoinRouteImport.update({
    id: '/join',
    path: '/join',
    getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthRouteRoute,
} as any)
const landingTermsRoute = landingTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => landingRouteRoute,
} as any)
const landingContactUsRoute = landingContactUsRouteImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => landingRouteRoute,
} as any)
const landingCalculatorRoute = landingCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => landingRouteRoute,
} as any)
const landingAboutRoute = landingAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => landingRouteRoute,
} as any)
const dashboardProfileRoute = dashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => dashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
    '/auth': typeof AuthRouteRouteWithChildren
    '/playground': typeof PlaygroundRoute
    '/dashboard': typeof dashboardDashboardRoute
    '/profile': typeof dashboardProfileRoute
    '/about': typeof landingAboutRoute
    '/calculator': typeof landingCalculatorRoute
    '/contact-us': typeof landingContactUsRoute
    '/terms': typeof landingTermsRoute
    '/auth/forgot-password': typeof AuthForgotPasswordRoute
    '/auth/join': typeof AuthJoinRoute
    '/auth/reset-password': typeof AuthResetPasswordRoute
    '/auth/sign-in': typeof AuthSignInRoute
    '/': typeof landingIndexRoute
}
export interface FileRoutesByTo {
    '/auth': typeof AuthRouteRouteWithChildren
    '/playground': typeof PlaygroundRoute
    '/dashboard': typeof dashboardDashboardRoute
    '/profile': typeof dashboardProfileRoute
    '/about': typeof landingAboutRoute
    '/calculator': typeof landingCalculatorRoute
    '/contact-us': typeof landingContactUsRoute
    '/terms': typeof landingTermsRoute
    '/auth/forgot-password': typeof AuthForgotPasswordRoute
    '/auth/join': typeof AuthJoinRoute
    '/auth/reset-password': typeof AuthResetPasswordRoute
    '/auth/sign-in': typeof AuthSignInRoute
    '/': typeof landingIndexRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/(dashboard)': typeof dashboardRouteRouteWithChildren
    '/(landing)': typeof landingRouteRouteWithChildren
    '/auth': typeof AuthRouteRouteWithChildren
    '/playground': typeof PlaygroundRoute
    '/(dashboard)/dashboard': typeof dashboardDashboardRoute
    '/(dashboard)/profile': typeof dashboardProfileRoute
    '/(landing)/about': typeof landingAboutRoute
    '/(landing)/calculator': typeof landingCalculatorRoute
    '/(landing)/contact-us': typeof landingContactUsRoute
    '/(landing)/terms': typeof landingTermsRoute
    '/auth/forgot-password': typeof AuthForgotPasswordRoute
    '/auth/join': typeof AuthJoinRoute
    '/auth/reset-password': typeof AuthResetPasswordRoute
    '/auth/sign-in': typeof AuthSignInRoute
    '/(landing)/': typeof landingIndexRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | '/auth'
        | '/playground'
        | '/dashboard'
        | '/profile'
        | '/about'
        | '/calculator'
        | '/contact-us'
        | '/terms'
        | '/auth/forgot-password'
        | '/auth/join'
        | '/auth/reset-password'
        | '/auth/sign-in'
        | '/'
    fileRoutesByTo: FileRoutesByTo
    to:
        | '/auth'
        | '/playground'
        | '/dashboard'
        | '/profile'
        | '/about'
        | '/calculator'
        | '/contact-us'
        | '/terms'
        | '/auth/forgot-password'
        | '/auth/join'
        | '/auth/reset-password'
        | '/auth/sign-in'
        | '/'
    id:
        | '__root__'
        | '/(dashboard)'
        | '/(landing)'
        | '/auth'
        | '/playground'
        | '/(dashboard)/dashboard'
        | '/(dashboard)/profile'
        | '/(landing)/about'
        | '/(landing)/calculator'
        | '/(landing)/contact-us'
        | '/(landing)/terms'
        | '/auth/forgot-password'
        | '/auth/join'
        | '/auth/reset-password'
        | '/auth/sign-in'
        | '/(landing)/'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
    landingRouteRoute: typeof landingRouteRouteWithChildren
    AuthRouteRoute: typeof AuthRouteRouteWithChildren
    PlaygroundRoute: typeof PlaygroundRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/playground': {
            id: '/playground'
            path: '/playground'
            fullPath: '/playground'
            preLoaderRoute: typeof PlaygroundRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/auth': {
            id: '/auth'
            path: '/auth'
            fullPath: '/auth'
            preLoaderRoute: typeof AuthRouteRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/(landing)': {
            id: '/(landing)'
            path: ''
            fullPath: ''
            preLoaderRoute: typeof landingRouteRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/(dashboard)': {
            id: '/(dashboard)'
            path: ''
            fullPath: ''
            preLoaderRoute: typeof dashboardRouteRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/(landing)/': {
            id: '/(landing)/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof landingIndexRouteImport
            parentRoute: typeof landingRouteRoute
        }
        '/auth/sign-in': {
            id: '/auth/sign-in'
            path: '/sign-in'
            fullPath: '/auth/sign-in'
            preLoaderRoute: typeof AuthSignInRouteImport
            parentRoute: typeof AuthRouteRoute
        }
        '/auth/reset-password': {
            id: '/auth/reset-password'
            path: '/reset-password'
            fullPath: '/auth/reset-password'
            preLoaderRoute: typeof AuthResetPasswordRouteImport
            parentRoute: typeof AuthRouteRoute
        }
        '/auth/join': {
            id: '/auth/join'
            path: '/join'
            fullPath: '/auth/join'
            preLoaderRoute: typeof AuthJoinRouteImport
            parentRoute: typeof AuthRouteRoute
        }
        '/auth/forgot-password': {
            id: '/auth/forgot-password'
            path: '/forgot-password'
            fullPath: '/auth/forgot-password'
            preLoaderRoute: typeof AuthForgotPasswordRouteImport
            parentRoute: typeof AuthRouteRoute
        }
        '/(landing)/terms': {
            id: '/(landing)/terms'
            path: '/terms'
            fullPath: '/terms'
            preLoaderRoute: typeof landingTermsRouteImport
            parentRoute: typeof landingRouteRoute
        }
        '/(landing)/contact-us': {
            id: '/(landing)/contact-us'
            path: '/contact-us'
            fullPath: '/contact-us'
            preLoaderRoute: typeof landingContactUsRouteImport
            parentRoute: typeof landingRouteRoute
        }
        '/(landing)/calculator': {
            id: '/(landing)/calculator'
            path: '/calculator'
            fullPath: '/calculator'
            preLoaderRoute: typeof landingCalculatorRouteImport
            parentRoute: typeof landingRouteRoute
        }
        '/(landing)/about': {
            id: '/(landing)/about'
            path: '/about'
            fullPath: '/about'
            preLoaderRoute: typeof landingAboutRouteImport
            parentRoute: typeof landingRouteRoute
        }
        '/(dashboard)/profile': {
            id: '/(dashboard)/profile'
            path: '/profile'
            fullPath: '/profile'
            preLoaderRoute: typeof dashboardProfileRouteImport
            parentRoute: typeof dashboardRouteRoute
        }
        '/(dashboard)/dashboard': {
            id: '/(dashboard)/dashboard'
            path: '/dashboard'
            fullPath: '/dashboard'
            preLoaderRoute: typeof dashboardDashboardRouteImport
            parentRoute: typeof dashboardRouteRoute
        }
    }
}

interface dashboardRouteRouteChildren {
    dashboardDashboardRoute: typeof dashboardDashboardRoute
    dashboardProfileRoute: typeof dashboardProfileRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
    dashboardDashboardRoute: dashboardDashboardRoute,
    dashboardProfileRoute: dashboardProfileRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
    dashboardRouteRouteChildren
)

interface landingRouteRouteChildren {
    landingAboutRoute: typeof landingAboutRoute
    landingCalculatorRoute: typeof landingCalculatorRoute
    landingContactUsRoute: typeof landingContactUsRoute
    landingTermsRoute: typeof landingTermsRoute
    landingIndexRoute: typeof landingIndexRoute
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
    landingAboutRoute: landingAboutRoute,
    landingCalculatorRoute: landingCalculatorRoute,
    landingContactUsRoute: landingContactUsRoute,
    landingTermsRoute: landingTermsRoute,
    landingIndexRoute: landingIndexRoute,
}

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
    landingRouteRouteChildren
)

interface AuthRouteRouteChildren {
    AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
    AuthJoinRoute: typeof AuthJoinRoute
    AuthResetPasswordRoute: typeof AuthResetPasswordRoute
    AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
    AuthForgotPasswordRoute: AuthForgotPasswordRoute,
    AuthJoinRoute: AuthJoinRoute,
    AuthResetPasswordRoute: AuthResetPasswordRoute,
    AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
    AuthRouteRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
    dashboardRouteRoute: dashboardRouteRouteWithChildren,
    landingRouteRoute: landingRouteRouteWithChildren,
    AuthRouteRoute: AuthRouteRouteWithChildren,
    PlaygroundRoute: PlaygroundRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
