/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthJoinRouteImport } from './routes/auth/join'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as testingVerifyFaceRecognizePageRouteImport } from './routes/(testing)/verify-face-recognize-page'
import { Route as privateProfileRouteImport } from './routes/(private)/profile'
import { Route as homeTermsRouteImport } from './routes/(home)/terms'
import { Route as homeContactUsRouteImport } from './routes/(home)/contact-us'
import { Route as homeCalculatorRouteImport } from './routes/(home)/calculator'
import { Route as homeAboutRouteImport } from './routes/(home)/about'
import { Route as privateDashboardIndexRouteImport } from './routes/(private)/dashboard/index'
import { Route as privateloanLoanApplicationCompleteRouteImport } from './routes/(private)/(loan)/loan-application-complete'
import { Route as privateloanLoanApplicationRouteImport } from './routes/(private)/(loan)/loan-application'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthJoinRoute = AuthJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const testingVerifyFaceRecognizePageRoute =
  testingVerifyFaceRecognizePageRouteImport.update({
    id: '/(testing)/verify-face-recognize-page',
    path: '/verify-face-recognize-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const privateProfileRoute = privateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => privateRouteRoute,
} as any)
const homeTermsRoute = homeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeContactUsRoute = homeContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeCalculatorRoute = homeCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeAboutRoute = homeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => homeRouteRoute,
} as any)
const privateDashboardIndexRoute = privateDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateloanLoanApplicationCompleteRoute =
  privateloanLoanApplicationCompleteRouteImport.update({
    id: '/(loan)/loan-application-complete',
    path: '/loan-application-complete',
    getParentRoute: () => privateRouteRoute,
  } as any)
const privateloanLoanApplicationRoute =
  privateloanLoanApplicationRouteImport.update({
    id: '/(loan)/loan-application',
    path: '/loan-application',
    getParentRoute: () => privateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/about': typeof homeAboutRoute
  '/calculator': typeof homeCalculatorRoute
  '/contact-us': typeof homeContactUsRoute
  '/terms': typeof homeTermsRoute
  '/profile': typeof privateProfileRoute
  '/verify-face-recognize-page': typeof testingVerifyFaceRecognizePageRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join': typeof AuthJoinRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof homeIndexRoute
  '/loan-application': typeof privateloanLoanApplicationRoute
  '/loan-application-complete': typeof privateloanLoanApplicationCompleteRoute
  '/dashboard/': typeof privateDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/about': typeof homeAboutRoute
  '/calculator': typeof homeCalculatorRoute
  '/contact-us': typeof homeContactUsRoute
  '/terms': typeof homeTermsRoute
  '/profile': typeof privateProfileRoute
  '/verify-face-recognize-page': typeof testingVerifyFaceRecognizePageRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join': typeof AuthJoinRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof homeIndexRoute
  '/loan-application': typeof privateloanLoanApplicationRoute
  '/loan-application-complete': typeof privateloanLoanApplicationCompleteRoute
  '/dashboard': typeof privateDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/(home)/about': typeof homeAboutRoute
  '/(home)/calculator': typeof homeCalculatorRoute
  '/(home)/contact-us': typeof homeContactUsRoute
  '/(home)/terms': typeof homeTermsRoute
  '/(private)/profile': typeof privateProfileRoute
  '/(testing)/verify-face-recognize-page': typeof testingVerifyFaceRecognizePageRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join': typeof AuthJoinRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/(home)/': typeof homeIndexRoute
  '/(private)/(loan)/loan-application': typeof privateloanLoanApplicationRoute
  '/(private)/(loan)/loan-application-complete': typeof privateloanLoanApplicationCompleteRoute
  '/(private)/dashboard/': typeof privateDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/playground'
    | '/about'
    | '/calculator'
    | '/contact-us'
    | '/terms'
    | '/profile'
    | '/verify-face-recognize-page'
    | '/auth/forgot-password'
    | '/auth/join'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/'
    | '/loan-application'
    | '/loan-application-complete'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/playground'
    | '/about'
    | '/calculator'
    | '/contact-us'
    | '/terms'
    | '/profile'
    | '/verify-face-recognize-page'
    | '/auth/forgot-password'
    | '/auth/join'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/'
    | '/loan-application'
    | '/loan-application-complete'
    | '/dashboard'
  id:
    | '__root__'
    | '/(home)'
    | '/(private)'
    | '/auth'
    | '/playground'
    | '/(home)/about'
    | '/(home)/calculator'
    | '/(home)/contact-us'
    | '/(home)/terms'
    | '/(private)/profile'
    | '/(testing)/verify-face-recognize-page'
    | '/auth/forgot-password'
    | '/auth/join'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/(home)/'
    | '/(private)/(loan)/loan-application'
    | '/(private)/(loan)/loan-application-complete'
    | '/(private)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  testingVerifyFaceRecognizePageRoute: typeof testingVerifyFaceRecognizePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/join': {
      id: '/auth/join'
      path: '/join'
      fullPath: '/auth/join'
      preLoaderRoute: typeof AuthJoinRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(testing)/verify-face-recognize-page': {
      id: '/(testing)/verify-face-recognize-page'
      path: '/verify-face-recognize-page'
      fullPath: '/verify-face-recognize-page'
      preLoaderRoute: typeof testingVerifyFaceRecognizePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/profile': {
      id: '/(private)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privateProfileRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(home)/terms': {
      id: '/(home)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof homeTermsRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/contact-us': {
      id: '/(home)/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof homeContactUsRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/calculator': {
      id: '/(home)/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof homeCalculatorRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/about': {
      id: '/(home)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(private)/dashboard/': {
      id: '/(private)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof privateDashboardIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(loan)/loan-application-complete': {
      id: '/(private)/(loan)/loan-application-complete'
      path: '/loan-application-complete'
      fullPath: '/loan-application-complete'
      preLoaderRoute: typeof privateloanLoanApplicationCompleteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(loan)/loan-application': {
      id: '/(private)/(loan)/loan-application'
      path: '/loan-application'
      fullPath: '/loan-application'
      preLoaderRoute: typeof privateloanLoanApplicationRouteImport
      parentRoute: typeof privateRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeAboutRoute: typeof homeAboutRoute
  homeCalculatorRoute: typeof homeCalculatorRoute
  homeContactUsRoute: typeof homeContactUsRoute
  homeTermsRoute: typeof homeTermsRoute
  homeIndexRoute: typeof homeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeAboutRoute: homeAboutRoute,
  homeCalculatorRoute: homeCalculatorRoute,
  homeContactUsRoute: homeContactUsRoute,
  homeTermsRoute: homeTermsRoute,
  homeIndexRoute: homeIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface privateRouteRouteChildren {
  privateProfileRoute: typeof privateProfileRoute
  privateloanLoanApplicationRoute: typeof privateloanLoanApplicationRoute
  privateloanLoanApplicationCompleteRoute: typeof privateloanLoanApplicationCompleteRoute
  privateDashboardIndexRoute: typeof privateDashboardIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateProfileRoute: privateProfileRoute,
  privateloanLoanApplicationRoute: privateloanLoanApplicationRoute,
  privateloanLoanApplicationCompleteRoute:
    privateloanLoanApplicationCompleteRoute,
  privateDashboardIndexRoute: privateDashboardIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthJoinRoute: typeof AuthJoinRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthJoinRoute: AuthJoinRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  testingVerifyFaceRecognizePageRoute: testingVerifyFaceRecognizePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
