export const ACCOUNT_CLOSURE_REASONS = [
    'Voluntary Withdrawal',
    'Inactive Membership',
    'Violation of Cooperative Rules',
    'Failure to Meet Financial Obligations',
    'Fraudulent Activities',
    'Transfer to Another Cooperative',
    'Death of Member',
    'Membership Revocation',
    'Request for Account Termination',
    'Other Personal Reasons',
    'Relocation Outside Service Area',
    'Better Opportunities Elsewhere',
    'Disagreement with Cooperative Direction',
    'Lack of Perceived Benefit',
    'Changes in Personal Circumstances (e.g., retirement, job change)',
    'Administrative Issues or Poor Service',
    'Merger or Dissolution of the Cooperative',
    'Financial Hardship',
    'Loss of Trust in Leadership',
    'Limited Engagement or Participation',
    'Becoming a Customer Only (if applicable)',
    'Desire for Simpler Financial Arrangements',
    'Conflict of Interest',
    'Feeling Undervalued or Unheard',
    'Changes in Cooperative Offerings',
    'Technological Disadvantages Compared to Other Options',
    'Success in Independent Ventures',
    'Inheritance or Windfall Allowing Independence',
    'Shifting Personal Values or Priorities',
    'Formation of a New, More Suitable Cooperative',
] as const
