import { useHotkeys } from 'react-hotkeys-hook'

import { useTransactionContext } from '../context/transaction-context'

export const useHotkeysTransaction = () => {
    const {
        form: transactionForm,
        memberScanner,
        selectedMemberId,
        history,
        accountPayment,
        accountPicker,
        handlers,
        navigate,
        finalPaymentOR,
        isAutoGeneratedForm,
        user_organization,
    } = useTransactionContext()

    useHotkeys(
        'Escape',
        (e) => {
            e.preventDefault()
            handlers.resetTransaction()
            navigate.clear()
        },
        { enableOnFormTags: true },
        [handlers, user_organization, transactionForm]
    )

    useHotkeys(
        'Enter',
        (e) => {
            e.preventDefault()
            if (!selectedMemberId && !memberScanner.open) {
                memberScanner.onOpenChange(true)
            }
        },
        [selectedMemberId, memberScanner.open]
    )
    useHotkeys(
        'Alt + W',
        (e) => {
            e.preventDefault()
            transactionForm.setFocus('reference_number')
        },
        { enableOnFormTags: true },
        [transactionForm]
    )
    useHotkeys(
        'Alt +  E',
        (e) => {
            e.preventDefault()
            const current = transactionForm.getValues('or_auto_generated')
            transactionForm.setValue('or_auto_generated', !current)
            if (current && user_organization) {
                transactionForm.setValue('reference_number', finalPaymentOR, {
                    shouldDirty: true,
                })
            }
        },
        { enableOnFormTags: true },
        [
            transactionForm,
            user_organization,
            finalPaymentOR,
            isAutoGeneratedForm,
        ]
    )
    useHotkeys(
        'f12',
        (e) => {
            e.preventDefault()
            if (accountPicker.open || accountPayment.open) return
            history.onOpenChange(!history.open)
        },
        {
            keydown: true,
            enableOnFormTags: true,
        },
        [accountPayment, accountPicker]
    )
}
