export const TAG_CATEGORY = [
    'account type',
    'alert',
    'calculation',
    'community',
    'cooperative',
    'digital',
    'governance',
    'insurance',
    'loan',
    'membership',
    'priority',
    'reserves',
    'security',
    'special',
    'status',
    'transaction type',
    'cash check voucher tag',
    'journal voucher tag',
    'adjustment tag',
    'account tag',
    'loan transaction tag',
] as const
